---
title: "Offensive Security Pentest Report"
author: []
date: "03/21/2022"
subject: "Offensive Security Pentest Report"
keywords: ["Offensive Security", "Pentest", "Report", "Audit", "GNU/Linux", "🍺"]
subtitle: "10.1.0.5, fd01::5"
lang: "en"
titlepage: true
titlepage-color: "2D2F3D"
titlepage-text-color: "FFFFFF"
titlepage-rule-color: "FFFFFF"
titlepage-rule-height: 2
book: true
classoption: oneside
code-block-font-size: \scriptsize
header-includes: |
  \usepackage{censor}
---
